---
# Copyright (C) 2020 Ruben Di Battista
# SPDX-License-Identifier: GPL-3.0-or-later

- name: (MacOS) Install wireguard package
  become: yes
  package:
    name: wireguard-go
    state: present
  tags:
    - wg-install

- name: (MacOS) Install wireguard-tools package
  become: yes
  package:
    name: wireguard-tools
    state: present
  tags:
    - wg-install
